change NI Arma MGs to open bolt
ARCOMM/arc_misc pull request #163
Opened 2022-02-27 23:10 UTC by Drofseh

2022-02-28 08:40 UTC, Freddo3000 commented
can you copy over this PR to https://github.com/toadie2k/NIArms?

2022-02-28 09:26 UTC, Drofseh commented
> can you copy over this PR to https://github.com/toadie2k/NIArms? Maybe check some of the other addons as well.

Do you mean just link to it?

2022-02-28 09:28 UTC, Freddo3000 commented
> > can you copy over this PR to [toadie2k/NIArms](https://github.com/toadie2k/NIArms)? Maybe check some of the other addons as well.
> 
> Do you mean just link to it?

New PR to NIArms with basically the same content. Maybe more if you find some other weapons that needs to be tweaked.

2022-02-28 09:32 UTC, Freddo3000 requested changes
Missing CfgPatches requiredAddons

2022-02-28 09:32 UTC, Freddo3000 commented on addons/weapons/CfgWeapons.hpp
> +    class hlc_M60e4_base : Rifle_Base_F {
`Rifle_Base_F` hasn't been opened here.

2022-02-28 09:42 UTC, Drofseh commented
> > > can you copy over this PR to [toadie2k/NIArms](https://github.com/toadie2k/NIArms)? Maybe check some of the other addons as well.
> > 
> > 
> > Do you mean just link to it?
> 
> New PR to NIArms with basically the same content. Maybe more if you find some other weapons that needs to be tweaked.

I'll consider it, but I don't really care too much tbh as I'm happy to always use the CUP version of the weapns.
And don't really want to go through the whole NI Arms catalogue.
Only doing this PR to appease those in arcomm who really want them.

> Missing CfgPatches requiredAddons

fixed

2022-05-09 15:58 UTC, Drofseh commented
I have no plans to PR to NIArms

2022-07-29 18:07 UTC, Freddo3000 commented
Closing as we dropped these mods in favour of the alternatives in CUP and/or FWA.

2022-07-29 18:07 UTC, closed without merging