Added loadout: pla_army_2010
ARCOMM/arc_misc pull request #50
Opened 2020-08-20 08:12 UTC by Freddo3000

2020-09-02 20:29 UTC, AChesheireCat requested changes

2020-09-02 20:29 UTC, AChesheireCat commented on addons/tmf_loadouts/loadouts/pla_army_2010.hpp
> +	backPack[] = {"CUP_B_Metis_Gun_Bag"};
Metis' ammo is stored in the tripod, would recommend swapping the gun out for the tripod.

2020-09-03 07:33 UTC, Freddo3000 commented on addons/tmf_loadouts/loadouts/pla_army_2010.hpp
> +	backPack[] = {"CUP_B_Kord_Gun_Bag"};
KORD only has a low tripod.

2020-09-03 17:40 UTC, AChesheireCat approved these changes

2020-09-03 17:40 UTC, merged