Added loadouts: cdf_army_fst/mnt/dst/snw
ARCOMM/arc_misc pull request #63
Opened 2020-09-01 14:18 UTC by Freddo3000

2020-09-02 20:23 UTC, AChesheireCat requested changes

2020-09-02 20:23 UTC, AChesheireCat commented on addons/tmf_loadouts/loadouts/cdf_army_template.hpp
> +};
AR and AAR only have a combined ammunition count of 540 which will limit their effectiveness. Consider adding a backpack to AR and giving him more ammunition?

2020-09-02 20:23 UTC, AChesheireCat commented on addons/tmf_loadouts/loadouts/cdf_army_template.hpp
> +	backpack[] = {"CUP_B_USMC_AssaultPack"};
Consider replacing with Kombat backpack (CUP_B_Kombat_Olive) to fit faction? If intended, disregard.

2020-09-02 20:23 UTC, AChesheireCat commented on addons/tmf_loadouts/loadouts/cdf_army_template.hpp
> +	backpack[] = {"CUP_B_USPack_Coyote"};
Replace with carryall equivalent? Unless intended, then disregard.

2020-09-28 16:09 UTC, BorderKeeper approved these changes
from cursory glance I see no issues with the loadouts. If they have been tested locally then lgtm.

2020-09-28 16:11 UTC, merged